Making the FightCovidDB singleton object creation synchronized
nic-delhi/AarogyaSetu_Android pull request #308
Opened 2020-05-28 21:49 UTC by hemanthvhr

The FightCovidDB Singleton object is can be accessed from different threads concurrently. So when creating the FightCovidDB object the first time, moved the object building logic inside synchronized block so multiple threads will have same database object.

2020-05-29 16:29 UTC, vidyasagardevireddy approved these changes

2020-05-29 16:31 UTC, vidyasagardevireddy requested changes

2020-05-29 16:31 UTC, vidyasagardevireddy commented on app/src/main/java/nic/goi/aarogyasetu/db/FightCovidDB.java
>          Context context = CoronaApplication.getInstance().getApplicationContext();
move this line into synchronized block.

2020-05-30 07:19 UTC, hemanthvhr commented on app/src/main/java/nic/goi/aarogyasetu/db/FightCovidDB.java
>          Context context = CoronaApplication.getInstance().getApplicationContext();
Hi, I did not quite understood this, can you please elaborate ? My confussion is we cannot declare a static variable of a class from inside the static method (where the synchronized block is present).

2020-05-31 17:29 UTC, vidyasagardevireddy approved these changes

2020-06-01 16:46 UTC, closed without merging